# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site title and description
title:              Open Projects of Margaret Catter Development
description:        Documentation about any publicly available works coming out of Margaret Catter Development and it's associated projects.
lang:               en

# Site subpath, e.g. /blog
baseurl:            "/OpenProjects"

# Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
permalink:          /:title/

# Site base hostname & protocol, e.g. http://example.com
url:                ""

# Site logo # e.g. logo.png, upload logo image file to /uploads/ folder
logo:               /assets/img/MCatterDevLogo_reAlice.png

navbar:
    sticky:         true
    search:         true
  
# Default author settings
author:
    name:           Imani
    title:          Lead Creative & Narrative Designer   
    avatar:         /assets/img/chibiPortraitpurple_kennolini.png

# Author settings, displayed on post and doc pages if front matter references author name e.g. author: peter
# authors:
#     john:
#       name:         John Brown
#       title:        Support     
#       avatar:       avatar-john.png
#     evan:
#       name:         Evan Wells
#       title:        Support    
#       avatar:       avatar-evan.png
#     sara:
#       name:         Sara Galen
#       title:        Lead Developer     
#       avatar:       avatar-sara.png
#     alex:
#       name:         Alex Koch
#       title:        Design Engineer     
#       avatar:       avatar-alex.png
#     daniel:
#       name:         Daniel Shultz
#       title:        Developer      
#       avatar:       avatar-daniel.png
#     tom:
#       name:         Tom Farrell
#       title:        Developer     
#       avatar:       avatar-tom.png

# Social icons displayed in footer
social:
    email: contact@margaretcatter.dev
    # website:
    # facebook:       
    # flickr:
    # dribbble:
    github: https://github.com/MargaretCatter
    # googleplus:
    # instagram:     
    # linkedin:
    # pinterest:
    twitter: https://twitter.com/mcatterdev
    # vimeo:          https://vimeo.com/
    # youtube:
    itch.io: https://margaretcatter.itch.io/
    revue: https://www.getrevue.co/profile/mcatterdev

# Share button
share:
    post:           true # Display share buttons on a post page
    doc:            true # Display share buttons on a doc page
    twitter:        username # Enable by adding Twitter handle 
    # facebook:       true # Enable by setting true (Facebook handle not required)

# Default footer image settings
footer:
    copyright:      Made by <a href="https://unbound.studio/">Unbound Studio</a> in Cleveland.

# Disqus comments shortname, requires Disqus account https://disqus.com/
# disqus:
#     shortname:      # 1234

# Google analytics code, get your code here https://www.google.com/analytics/
google_analytics: G-55J8S57NFQ

# Number of posts displayed on blog page
paginate:           15

# Blog path
paginate_path:      "/blog/:num/"

# Path to post content assets directory i.e post images, pdfs etc
uploads:            /uploads/

# Build settings
markdown:           kramdown
highlighter:        rouge

gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-avatar
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules

sass:
  style:            compressed

collections:
  docs:
    output:         true
  faqs:
    output:         false
  changelogs:
    output:         true

# Defaults
defaults:
  # _posts
  - scope:
      path:         ""
      type:         posts
    values:
      layout:       post
  # _docs
  - scope:
      path:         ""
      type:         docs
    values:
      layout:       doc
